### ISSUE TITLE
Bump zone.js peerDependency

### ISSUE THREAD

**Issue by 4kochi** [thymikee/jest-zone-patch#3]
I use the new beta of npm5. But it can't create a `package.lock.json` because of the following error:

`jest-zone-patch@0.0.6 requires a peer of zone.js@^0.7.5 but none was installed.`

Does your repo depend on zone.js `0.7.x` or is it also compatible with zone.js version greater than `0.7`? Because we use zone.js `0.8.x`

**Comment by thymikee** [comment]
I see this warning in yarn too but I totally don't get it. I set it to ^0.7 because I know it's compatible with everything since this  version (up to next major). But I can also bump it, if this is how they work

**Comment by 4kochi** [comment]
The semver range of `^0.7` is `>= 0.7 < 0.8.0`. Because versions < 1.0 are treated specially. See https://docs.npmjs.com/misc/semver

 I guess `>=0.7` should work.

**Comment by thymikee** [comment]
Oh, now it makes sense! Would you like to make a PR with tat change?

**Comment by 4kochi** [comment]
No problem.

**Comment by 4kochi** [comment]
See #4
