### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by mchandler-cng** [thymikee/jest-zone-patch#6]
Is there any way that we could get a new release for this package? A commit was made in September allowing empty/pending tests, but since there hasn't been a release made since then, `jest-preset-angular` cannot pick up that change. It would be quite useful for our project to have pending tests!

As an aside: Thanks for the work that you've done on both of these projects. It's great to be able to use jest with Angular. Sure beats the default tools by a wide margin.

**Comment by thymikee** [comment]
Latest version should already include this commit, I just forgot to push the refs 😅 
https://www.npmjs.com/package/jest-zone-patch points to `v0.0.8`

**Comment by thymikee** [comment]
Yea, unpkg confirms it's there: https://unpkg.com/jest-zone-patch@0.0.8/index.js
Closing then. Glad it's useful! :)

**Comment by mchandler-cng** [comment]
@thymikee Awesome. Thanks again!

**Comment by returnlytom** [comment]
Also want to say thanks for your hard work @thymikee Your blog post on testing Angular w/ Jest was very helpful

**Comment by thymikee** [comment]
❤️
